from http import HTTPStatus

PAGE_SIZE = 12

PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"

HTTP_200_OK = HTTPStatus.OK
HTTP_400_BAD_REQUEST = HTTPStatus.BAD_REQUEST
HTTP_403_FORBIDDEN = HTTPStatus.FORBIDDEN

PHONE_REGEX = r"^\+7\d{10}$"
GITHUB_DOMAIN = "github.com"

ABOUT_MAX_LENGTH = 256
NAME_MAX_LENGTH = 124
PHONE_MAX_LENGTH = 12
